package collections_java_api_2025.list;

import java.time.LocalDate;

import collections_java_api_2025.map.AgendaContato;
import collections_java_api_2025.map.AgendaEventos;
import collections_java_api_2025.map.EstoqueProdutos;
import collections_java_api_2025.map.Evento;
import collections_java_api_2025.ordenacao.CadastroProduto;
import collections_java_api_2025.ordenacao.Pessoa;
import collections_java_api_2025.ordenacao.Produto;
import collections_java_api_2025.set.AgendaContatos;
import collections_java_api_2025.set.ConjuntoConvidados;
import collections_java_api_2025.set.Contato;
import collections_java_api_2025.set.Convidado;

public class Main {

	public static void main(String[] args) {

		ListaTarefa lista = new ListaTarefa();

		System.out.println("Lista de Tarefas:");
		lista.addTarefa("Estudar Java");
		lista.addTarefa("Praticar Collections");
		lista.addTarefa("Criar um projeto");
		lista.addTarefa("Revisar conceitos");
		lista.addTarefa("Participar de um curso online");
		lista.addTarefa("Participar de um curso online");
		lista.addTarefa("Participar de um curso online");
		System.out.println("-----------------------------------------------------------------");
		lista.imprimirListaDeTarefas();
		System.out.println("Total de Tarefas: " + lista.obterTotalTarefas());
		System.out.println("-----------------------------------------------------------------");
		System.out.println("Removendo a tarefa: Participar de um curso online");
		lista.removeTarefa("Participar de um curso online");
		System.out.println("Lista de Tarefas:");
		lista.imprimirListaDeTarefas();
		System.out.println("Total de Tarefas: " + lista.obterTotalTarefas());
		System.out.println("-----------------------------------------------------------------");
		System.out.println("Buscando a tarefa: Estudar Java");
		lista.findTarefa("Estudar Java");
		System.out.println("-----------------------------------------------------------------");
		System.out.println("Buscando a tarefa: Tarefa Inexistente");
		lista.findTarefa("Tarefa Inexistente");

		System.out.println("-----------------------------------------------------------------");
		CarrinhoDeCompras carrinho = new CarrinhoDeCompras();
		carrinho.addItem("Notebook", 2500.00, 1);
		carrinho.addItem("Mouse", 50.00, 2);
		carrinho.addItem("Teclado", 100.00, 1);
		carrinho.addItem("Monitor", 800.00, 1);
		carrinho.addItem("Cadeira Gamer", 1200.00, 1);
		carrinho.addItem("Cadeira Gamer", 1200.00, 1);
		carrinho.addItem("Cadeira Gamer", 1200.00, 1);
		carrinho.exibirItemsCarrinho();
		carrinho.calcularValorTotal();
		System.out.println("-----------------------------------------------------------------");
		carrinho.removeItem("Cadeira Gamer");
		System.out.println("Itens no carrinho após remoção:");
		carrinho.exibirItemsCarrinho();
		carrinho.calcularValorTotal();
		System.out.println("-----------------------------------------------------------------");

		CatalogoLivros catalogo = new CatalogoLivros();
		catalogo.addLivro("Java: Como Programar", "Deitel", 2020);
		catalogo.addLivro("Effective Java", "Joshua Bloch", 2018);
		catalogo.addLivro("Clean Code", "Robert C. Martin", 2019);
		catalogo.addLivro("Java Concurrency in Practice", "Brian Goetz", 2017);
		catalogo.addLivro("Head First Java", "Kathy Sierra", 2021);
		catalogo.addLivro("Head First Java", "Kathy Sierra", 2021);
		catalogo.addLivro("Head First Java", "Kathy Sierra", 2021);
		catalogo.imprimirCatalogo();
		System.out.println("-----------------------------------------------------------------");
		catalogo.pesquisarPorAutor("Deitel");
		System.out.println("-----------------------------------------------------------------");
		catalogo.pesquisarPorIntervaloAnos(2018, 2020);
		System.out.println("-----------------------------------------------------------------");
		catalogo.pesquisarPorTitulo("Effective Java");
		System.out.println("-----------------------------------------------------------------");
		OrdenacaoPessoas ordenacaoPessoas = new OrdenacaoPessoas();
		ordenacaoPessoas.addPessoa(new Pessoa("Alice", 30, 1.65));
		ordenacaoPessoas.addPessoa(new Pessoa("Bob", 25, 1.80));
		ordenacaoPessoas.addPessoa(new Pessoa("Charlie", 35, 1.75));
		System.out.println("Lista de Pessoas:");
		ordenacaoPessoas.imprimeListaPessoas();
		System.out.println("-----------------------------------------------------------------");
		System.out.println("Pessoas ordenadas por idade:");
		ordenacaoPessoas.ordenarPorIdade();
		ordenacaoPessoas.imprimeListaPessoasOrdenadasPorIdade();
		System.out.println("-----------------------------------------------------------------");
		System.out.println("Pessoas ordenadas por altura:");
		ordenacaoPessoas.ordenarPorAltura();
		ordenacaoPessoas.imprimeListaPessoasOrdenadasPorAltura();

		System.out.println("-----------------------------------------------------------------");
		ConjuntoConvidados conjuntoConvidados = new ConjuntoConvidados();
		conjuntoConvidados.addConvidado(new Convidado("João", 101));
		conjuntoConvidados.addConvidado(new Convidado("Maria", 102));
		conjuntoConvidados.addConvidado(new Convidado("Pedro", 103));
		conjuntoConvidados.addConvidado(new Convidado("Ana", 104));
		conjuntoConvidados.addConvidado(new Convidado("Lucas", 105));
		conjuntoConvidados.addConvidado(new Convidado("João", 101));
		conjuntoConvidados.exibirConvidados();
		System.out.println("-----------------------------------------------------------------");
		conjuntoConvidados.removerCandidatoPorNumeroConvite(102);
		conjuntoConvidados.exibirConvidados();
		System.out.println("-----------------------------------------------------------------");
		conjuntoConvidados.removerCandidatoPorNumeroConvite(999);
		conjuntoConvidados.exibirConvidados();
		System.out.println("-----------------------------------------------------------------");
		AgendaContatos agendaContatos = new AgendaContatos();
		agendaContatos.addContato(new Contato("Carlos", "1234-5678"));
		agendaContatos.addContato(new Contato("Ana", "9876-5432"));
		agendaContatos.addContato(new Contato("João Ricardo", "5555-5555"));
		agendaContatos.addContato(new Contato("João Neves", "3333-5555"));
		agendaContatos.addContato(new Contato("Maria", "1111-1111"));
		agendaContatos.addContato(new Contato("Carlos", "1234-5678"));
		agendaContatos.exibirContatos();
		System.out.println("-----------------------------------------------------------------");
		System.out.println("Pesquisando contatos por nome: Ricardo");
		agendaContatos.pesquisarPorNome("Ricardo");
		System.out.println("-----------------------------------------------------------------");
		System.out.println("Pesquisando contatos por nome: Roberto");
		agendaContatos.pesquisarPorNome("Roberto");
		System.out.println("-----------------------------------------------------------------");
		System.out.println("Atualizando número de contato: João para 2222-2222");
		agendaContatos.atualizarNumeroContato("João", "2222-2222");
		System.out.println("Atualizando número de contato: João Ricardo para 3333-2222");
		agendaContatos.atualizarNumeroContato("João Ricardo", "3333-2222");
		System.out.println("Atualizando número de contato: Roberto para 3333-3333 (não existe)");
		agendaContatos.atualizarNumeroContato("Roberto", "3333-3333");
		agendaContatos.exibirContatos();
		System.out.println("-----------------------------------------------------------------");
		CadastroProduto cadastroProduto = new CadastroProduto();
		cadastroProduto.adicionaProduto(new Produto(1000L,"Notebook", 2500.00, 1));
		cadastroProduto.adicionaProduto(new Produto(1001L,"Mouse", 50.00, 2));
		cadastroProduto.adicionaProduto(new Produto(1002L,"Teclado", 100.00, 1));
		cadastroProduto.adicionaProduto(new Produto(1003L,"Monitor", 800.00, 1));
		cadastroProduto.adicionaProduto(new Produto(1004L,"Cadeira Gamer", 1200.00, 1));
		cadastroProduto.adicionaProduto(new Produto(1005L,"Cadeira Gamer", 1200.00, 1));
		cadastroProduto.adicionaProduto(new Produto(1006L,"Cadeira Gamer", 1200.00, 1));
		System.out.println("Exibindo produtos cadastrados:");
		cadastroProduto.exibirProdutos();
		System.out.println("Exibindo produtos por nome em ordem alfabética:");
		cadastroProduto.exibirProdutosPorNomeEmOrdemAlfabetica();
		System.out.println("-----------------------------------------------------------------");
		System.out.println("Exibindo produtos por preço em ordem crescente:");
		cadastroProduto.exibirProdutosPorPrecoEmOrdemCrescente();
		System.out.println("-----------------------------------------------------------------");
		AgendaContato agendaContato = new AgendaContato();
		agendaContato.adicionarContato("João", "1234-5678");
		agendaContato.adicionarContato("Maria", "9876-5432");
		agendaContato.adicionarContato("Pedro", "5555-5555");
		agendaContato.adicionarContato("Ana", "3333-3333");
		agendaContato.adicionarContato("Lucas", "1111-1111");
		agendaContato.adicionarContato("João", "1234-5678");
		System.out.println("Agenda de Contatos:");
		System.out.println("-----------------------------------------------------------------");
		agendaContato.exibirContatos();
		System.out.println("-----------------------------------------------------------------");
		System.out.println("Buscando contato: João");
		String telefoneJoao = agendaContato.buscarContato("João");
		if (telefoneJoao != null) {
			System.out.println("Telefone de João: " + telefoneJoao);
		}		
		System.out.println("-----------------------------------------------------------------");
		System.out.println("Buscando contato: Maria");
		String telefoneMaria = agendaContato.buscarContato("Maria");
		if (telefoneMaria != null) {
			System.out.println("Telefone de Maria: " + telefoneMaria);
		}	
		System.out.println("-----------------------------------------------------------------");
		System.out.println("Removendo contato: Pedro");
		agendaContato.removerContato("Pedro");
		agendaContato.exibirContatos();
		System.out.println("-----------------------------------------------------------------");
		System.out.println("Removendo contato: Ana");
		agendaContato.removerContato("Ana");
		agendaContato.exibirContatos();
		System.out.println("-----------------------------------------------------------------");
		System.out.println("Removendo contato: Lucas");
		agendaContato.removerContato("Lucas");
		agendaContato.exibirContatos();
		System.out.println("-----------------------------------------------------------------");
		System.out.println("Removendo contato: Roberto (não existe)");
		agendaContato.removerContato("Roberto");
		agendaContato.exibirContatos();
		System.out.println("-----------------------------------------------------------------");
		EstoqueProdutos estoqueProdutos = new EstoqueProdutos();
		estoqueProdutos.adicionarProduto(new Produto(1000L, "Notebook", 2500.00, 1));
		estoqueProdutos.adicionarProduto(new Produto(1001L, "Mouse", 50.00, 2));
		estoqueProdutos.adicionarProduto(new Produto(1002L, "Teclado", 100.00, 1));
		estoqueProdutos.adicionarProduto(new Produto(1003L, "Monitor", 800.00, 1));
		estoqueProdutos.adicionarProduto(new Produto(1004L, "Cadeira Gamer", 1200.00, 1));
		estoqueProdutos.adicionarProduto(new Produto(1005L, "Cadeira Gamer", 1200.00, 1));
		estoqueProdutos.adicionarProduto(new Produto(1006L, "Cadeira Gamer", 1200.00, 3));
		System.out.println("Exibindo produtos no estoque:");
		estoqueProdutos.exibirProdutos();
		System.out.println("-----------------------------------------------------------------");
		System.out.println("Calculando valor total do estoque:");
		estoqueProdutos.calcularValorTotalEstoque();
		System.out.println("-----------------------------------------------------------------");
		estoqueProdutos.obterProdutoMaisCaro();
		System.out.println("-----------------------------------------------------------------");
		estoqueProdutos.obterProdutoMaisBarato();
		System.out.println("-----------------------------------------------------------------");
		System.out.println("Adicionando produto com código duplicado:");
		estoqueProdutos.adicionarProduto(new Produto(1000L, "Notebook", 2500.00, 1));
		System.out.println("-----------------------------------------------------------------");
		System.out.println("Atualizando produto existente:");
		estoqueProdutos.atualizandoProduto(new Produto(1001L, "Mouse", 55.00, 5));
		System.out.println("Exibindo produtos no estoque após atualização:");
		estoqueProdutos.exibirProdutos();
		System.out.println("-----------------------------------------------------------------");
		System.out.println("Removendo produto: Teclado");
		estoqueProdutos.removerProduto(1002L);
		System.out.println("Exibindo produtos no estoque após remoção:");
		estoqueProdutos.exibirProdutos();
		System.out.println("-----------------------------------------------------------------");
		System.out.println("Calculando valor total do estoque após remoção:");
		estoqueProdutos.calcularValorTotalEstoque();
		System.out.println("-----------------------------------------------------------------");
		estoqueProdutos.obterProdutoMaiorQuantidadeXValorTotalNoEstoque();
		System.out.println("-----------------------------------------------------------------");
		AgendaEventos agendaEventos = new AgendaEventos();
		agendaEventos.adicionarEvento(new Evento(LocalDate.of(2025, 7, 18), "Show de Rock", "Banda X"));
		agendaEventos.adicionarEvento(new Evento(LocalDate.of(2025, 8, 15), "Festival de Jazz", "Banda Y"));
		agendaEventos.adicionarEvento(new Evento(LocalDate.of(2025, 8, 10), "Teatro", "Peça Z"));
		agendaEventos.adicionarEvento(new Evento(LocalDate.of(2025, 9, 20), "Festival de Música", "Artista A"));
		agendaEventos.adicionarEvento(new Evento(LocalDate.of(2025, 9, 15), "Festival de Jazz", "Banda Y"));
		agendaEventos.adicionarEvento(new Evento(LocalDate.of(2024, 12, 25), "Natal", "Celebração de Natal"));
		agendaEventos.adicionarEvento(new Evento(LocalDate.of(2025, 10, 15), "Festival de Jazz", "Banda Y"));
		agendaEventos.adicionarEvento(new Evento(LocalDate.of(2025, 10, 15), "Festival de Jazz", "Banda Y"));
		System.out.println("Agenda de Eventos:");
		agendaEventos.exibirEventosOrdemCrescente();
		System.out.println("-----------------------------------------------------------------");
		System.out.println("Obtendo próximo evento!");
		agendaEventos.obterProximoEvento();
		System.out.println("-----------------------------------------------------------------");
	}
}